service: danae

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  # environment:
  #   SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  echo:
    handler: handler.echo
    events:
      - http:
          path: echo
          method: post
  checkUrl:
    handler: handler.checkUrl
    events:
      - http:
          path: check
          method: post

# custom:
#   bundle:
#     excludeFiles: "**/*.test.ts"    # Exclude files from Webpack that match the glob